<?php
$auto_reviews_en = array(
    array("name" => "Jure M.", "text" => "Barva bokserica ostaje ista i nakon puno pranja, ništa ne blijedi."),
    array("name" => "Roko P.", "text" => "Noriks boksarice su me resnično presenetile. Tkanina je mekana, ne grebe i ne stišće tamo gdje ne treba."),
    array("name" => "Marko S.", "text" => "Stvarno udobne boksarice za cijeli dan, ne osjetim ih na sebi."),
    array("name" => "Tomo R.", "text" => "Gumica u struku je čvrsta, ali ne zateže. Ne urezuje se u kožu."),
    array("name" => "Josip D.", "text" => "Prozračne i lagane, popolne za posao i teretanu."),
    array("name" => "Luka M.", "text" => "Boksarice drže oblik i nakon večstrukog pranja, nigdje se ne rastežu."),
    array("name" => "Kristijan C.", "text" => "Materijal je gladak na koži, nema nikakvog iritirajućeg šava."),
    array("name" => "Davor V.", "text" => "Nakon cijelog dana nošenja sve stoji na svom mjestu, ništa se ne podiže."),
    array("name" => "Mislav L.", "text" => "Noriks boksarice izgledaju kakovostno čim ih primiš u ruku. Vse pohvale."),
    array("name" => "Petar G.", "text" => "Nosim jih že več tednov, brez muckanja in brez raztegovanja materiala."),
    array("name" => "Ante B.", "text" => "Popoln kroj, prate telo, ali ne stišću. Baš taman."),
    array("name" => "Filip J.", "text" => "Nogavice se ne uvlače prema gore, što mi je ogroman plus."),
    array("name" => "Nikola R.", "text" => "Noriks boksarice su mi postale prva opcija u ladici, vedno ih prvo uzmem."),
    array("name" => "Matija S.", "text" => "Nema neprijetnog znojenja, tkanina lijepo diše."),
    array("name" => "Domagoj K.", "text" => "Izgleda da će trajati dugo, šavovi su zelo uredni i čvrsti."),
    array("name" => "Ivan H.", "text" => "Odličen omjer cijene i kakovosti, bolje od puno skupljih brendova."),
    array("name" => "Zvonimir P.", "text" => "Ne podižu se ispod hlača, sve ostaje ravno i na svom mjestu."),
    array("name" => "Branimir N.", "text" => "Boksarice stoje odlično iako sam između dvije veličine."),
    array("name" => "Renato T.", "text" => "Gumica ne gubi elastičnost ni nakon več pranja."),
    array("name" => "Andrej M.", "text" => "Noriks boksarice su idealne i za posao i za trening – ne mijenjam več brend."),
    array("name" => "Dino K.", "text" => "Stvarno osjećaj kao pidžama, a izgledaju uredno i moderno."),
    array("name" => "Leon B.", "text" => "Lijepo oblikuju stražnjicu, bez onog vrećastog izgleda."),
    array("name" => "Darko Z.", "text" => "Materijal se brzo suši, super za putovanja."),
    array("name" => "Vjekoslav H.", "text" => "Noriks boksarice ne žuliju ni pri dugom sjedenju u uredu."),
    array("name" => "Krešimir F.", "text" => "Nema grubih etiketa koje smetaju, sve je fino obrađeno."),
    array("name" => "Tihomir K.", "text" => "Nosim ih cijeli dan i navečer se i dalje osjećam udobno."),
    array("name" => "Borna V.", "text" => "Boksarice se ne okreću i ne savijaju ispod traperica."),
    array("name" => "Mario Č.", "text" => "Noriks kroj lijepo prati liniju nogu i ne stvara nabore."),
    array("name" => "Stjepan C.", "text" => "Kupil sem en par, nato pa takoj naročil še tri. To pove vse."),
    array("name" => "Hrvoje N.", "text" => "Barva ostaje postojana, čak i na crnim boksericama nakon več pranja."),
    array("name" => "Danijel L.", "text" => "Nema neprijetnog mirisa ni nakon napornog dana, super prozračnost."),
    array("name" => "Goran B.", "text" => "Noriks boksarice su mi zamijenile sve stare, izbacio sam ostale iz ormara."),
    array("name" => "Željko R.", "text" => "Nigdje ne stišće, a opet daje osjećaj sigurnosti i opore."),
    array("name" => "Vedran M.", "text" => "Idealne za ljeto, ne lijepe se za kožu."),
    array("name" => "Siniša J.", "text" => "Šavovi su glatki, nema trljanja ni kod duljeg hodanja."),
    array("name" => "Vlado N.", "text" => "Tkanina je dovoljno gusta da ne prozire, ali opet lagana."),
    array("name" => "Nino E.", "text" => "Noriks boksarice drže sve na mjestu i tijekom treninga."),
    array("name" => "Saša K.", "text" => "Jako sam zadovoljan. Napokon donje rublje koje ne živcira."),
    array("name" => "Igor B.", "text" => "Ni nakon sušilice se nisu skupile niti izobličile."),
    array("name" => "Janko T.", "text" => "Boksarice stoje odlično i visokim osobama poput mene."),
    array("name" => "Tvrtko G.", "text" => "Odličen kroj u struku i preko bedara, ništa ne visi."),
    array("name" => "Boris R.", "text" => "Noriks boksarice su toliko udobne da ih jedva osjetim."),
    array("name" => "Karol D.", "text" => "Nosim ih i na posao i u teretanu – sve odrade bez problema."),
    array("name" => "Mladen H.", "text" => "Gumica ne ostavlja tragove na koži, a svejedno dobro drži."),
    array("name" => "Zoran P.", "text" => "Ugodne na dodir, nema onog sintetičkog osjećaja."),
    array("name" => "Dražen K.", "text" => "Prve boksarice s kojima nemam problema s podizanjem nogavica."),
    array("name" => "Fran M.", "text" => "Noriks je pogodio mjeru – ni preuske ni preširoke."),
    array("name" => "Nikša H.", "text" => "Kad ih obučem ujutro, ne moram ih 'namještati' tijekom dana."),
    array("name" => "Žarko V.", "text" => "Odlične i za duge vožnje, nema žulinja."),
    array("name" => "Marin J.", "text" => "Noriks boksarice ne gube formu ni nakon mjesec dana pranja."),
    array("name" => "Toni P.", "text" => "Lijepo leže ispod odijela, ništa se ne preslikava."),
    array("name" => "Andrija K.", "text" => "Uz ove boksarice več ne razmišljam što obleči dolje – sve ostalo je lošije."),
    array("name" => "Lovro B.", "text" => "Boksarice su mekane, ali djeluju zelo izdržljivo."),
    array("name" => "Karlo Z.", "text" => "Nema iritacija ni kad je vruće, materijal dobro diše."),
    array("name" => "Zdeslav L.", "text" => "Ovo su mi najudobnije boksarice do zdaj, bez pretjerivanja."),
    array("name" => "Viktor P.", "text" => "Noriks boksarice su taman duljine, ne režu u preponama."),
    array("name" => "Damir G.", "text" => "Dojam je kao da nosiš premium brend, a cijena je normalna."),
    array("name" => "Alen S.", "text" => "Šavovi su napravljeni tako da ih gotovo ni ne osjetiš."),
    array("name" => "Kristian J.", "text" => "Boksarice ostaju glatke, ne pelcaju se i ne hvataju dlačice."),
    array("name" => "Luka F.", "text" => "Odlične boksarice za vsak dan – več ni ne razmišljam o drugim."),
    array("name" => "Mario R.", "text" => "I nakon intenzivnog treninga sve stoji na svom mjestu."),
    array("name" => "Ante C.", "text" => "Noriks boksarice su me ugodno presenetile – udobje 10/10."),
    array("name" => "Ivan O.", "text" => "Kupil sem več parov in uporabljam samo še te."),
    array("name" => "Stipe V.", "text" => "Ne uvijaju se ni kad nosim uske hlače."),
    array("name" => "Dino L.", "text" => "Noriks tkanina ne zadržava vlagu, brzo se osuše."),
    array("name" => "Goran U.", "text" => "Odličen izbor za ljude koji puno sjede za računalom."),
    array("name" => "Miro E.", "text" => "Boksarice izgledaju kao nove i nakon več tednov korištenja."),
    array("name" => "Bruno Č.", "text" => "Nema nepotrebnih natpisa i uzoraka, jednostavne i muževne."),
    array("name" => "Nikola K.", "text" => "Popoln balans između udobjei i opore."),
    array("name" => "Vjeko J.", "text" => "Noriks boksarice ne režu ni u struku ni na bedrima."),
    array("name" => "Srećko P.", "text" => "Lako se peru i brzo suhe, praktično za vsak dan."),
    array("name" => "Leo M.", "text" => "Boje su baš kako izgledaju na slikama, nema iznenađenja."),
    array("name" => "Damjan D.", "text" => "Nakon nekoliko sati na vrućini i dalje udobne, bez iritacija."),
    array("name" => "Dorian S.", "text" => "Noriks boksarice se ne vidi kroz tanke hlače, što mi je zelo bitno."),
    array("name" => "Adrian K.", "text" => "Gumica je široka i stabilna, ne okreće se i ne rola."),
    array("name" => "Rene H.", "text" => "Osjećam se puno ugodnije tijekom dana otkad nosim ove boksarice."),
    array("name" => "Zlatko R.", "text" => "Boksarice su dobro krojene za muškarce jače građe."),
    array("name" => "Tomislav E.", "text" => "Noriks boksarice odrade i posao i trening bez problema."),
    array("name" => "Krešo L.", "text" => "Končno donje rublje koje ne moram stalno popravljati."),
    array("name" => "Nenad K.", "text" => "Z nakupom sem zelo zadovoljen, zagotovo jih vzamem še."),
    array("name" => "Dragan V.", "text" => "Boksarice ne klize prema dolje, drže se struka cijeli dan."),
    array("name" => "Slaven T.", "text" => "Noriks je pogodio gustoću tkanine – nije debela, ali nije ni tanka."),
    array("name" => "Alberto N.", "text" => "Odlične za svakodnevicu, ali i za putovanja."),
    array("name" => "Zrinko B.", "text" => "Nakon pranja nema deformacija, sve ostaje ravno."),
    array("name" => "Ilija S.", "text" => "Noriks boksarice ne stišću prepone, što mi je vedno bio problem kod drugih."),
    array("name" => "Mario L.", "text" => "Zelo udobne, čak i kad sam cijeli dan u pokretu."),
    array("name" => "Lovro Š.", "text" => "Boksarice se ne urezuju u bokove, kroj je resnično dobar."),
    array("name" => "Željko K.", "text" => "Ne pišem često recenzije, ali ove boksarice to zaslužuju."),
    array("name" => "Ante Ž.", "text" => "Noriks boksarice podižu razinu udobjei na potpuno novu razinu."),
    array("name" => "Vlado R.", "text" => "Jednom kad ih probaš, druge ti več ne pašu."),
    array("name" => "Goran Č.", "text" => "Hitra dostava in vrhunski izdelek, vse priporočilo."),
     array("name" => "Vilim S.", "text" => "Boksarice popolno prianjaju, nema podizanja nogavica."),
    array("name" => "Oleg T.", "text" => "Tkanina je toliko mekana da ih jedva osjetim."),
    array("name" => "Stjepan I.", "text" => "Nosim ih cijeli dan bez ikakve nelagode."),
    array("name" => "Karlo H.", "text" => "Gumica je odlična, ne urezuje se i ne rola."),
    array("name" => "Darin P.", "text" => "Nakon pranja ostaju iste, bez rastezanja."),
    array("name" => "Adrian V.", "text" => "Super materijal, prozračan i udoben."),
    array("name" => "Leon M.", "text" => "Taman dužina, ništa se ne pomiče."),
    array("name" => "Augustin J.", "text" => "Noriks boksarice su mi postale prva opcija."),
    array("name" => "Kristijan U.", "text" => "Nema znojenja ni nakon treninga."),
    array("name" => "Dejan T.", "text" => "Očekivao sam dobro, ali ovo je top."),
    array("name" => "Juraj A.", "text" => "Mekane, ali čvrste — odličen balans."),
    array("name" => "Darko S.", "text" => "Ne uvlače se u hlače, sve stoji ravno."),
    array("name" => "Benedikt K.", "text" => "Končno boksarice koje ne stišću."),
    array("name" => "Loren P.", "text" => "Jako kakovostn materijal."),
    array("name" => "Ignac R.", "text" => "Sve pohvale, kupujem opet."),
    array("name" => "Marin D.", "text" => "Stvarno ugodne na koži."),
    array("name" => "Miron B.", "text" => "Šavovi su nevjerojatno dobro obrađeni."),
    array("name" => "René M.", "text" => "Nosim ih u uredu i na treningu — odlične."),
    array("name" => "Teo Z.", "text" => "Ovo su jedine boksarice koje več želim nositi."),
    array("name" => "Branimir Š.", "text" => "Gumica je jaka, ali ne steže."),
    array("name" => "Valentino R.", "text" => "Ne zadržavaju vlagu, što mi je super."),
    array("name" => "Patrik L.", "text" => "Udobne i nakon več sati nošenja."),
    array("name" => "Tomo U.", "text" => "Nema iritacija, čak ni po vrućini."),
    array("name" => "Mario Š.", "text" => "Zelo kakovostno izrađene."),
    array("name" => "Nikola D.", "text" => "Ne pomiču se tijekom vježbanja."),
    array("name" => "Vito P.", "text" => "Nakon 10 pranja iste kao nove."),
    array("name" => "Zdravko T.", "text" => "Boksarice koje končno imaju smisla."),
    array("name" => "Lovre K.", "text" => "Tkanina ne grebe i ne svrbim."),
    array("name" => "Ernest B.", "text" => "Odlične za vsak dan."),
    array("name" => "Roman V.", "text" => "Za moju građu su popolne."),
    array("name" => "Markian G.", "text" => "Dobre i za zimu i za ljeto."),
    array("name" => "Kristo H.", "text" => "Ne izgledaju iznošeno ni nakon mjesec dana."),
    array("name" => "Tibor A.", "text" => "Kroj mi popolno odgovara."),
    array("name" => "Fabijan S.", "text" => "Udobne čak i tijekom cijelog dana vožnje."),
    array("name" => "Damjan K.", "text" => "Najboljše boksarice koje sam kupil."),
    array("name" => "Sebastijan M.", "text" => "Materijal je premium kakovosti."),
    array("name" => "Zoran U.", "text" => "Ne stišću bedra, što mi je vedno bio problem."),
    array("name" => "Krešimir B.", "text" => "Drže sve na mjestu."),
    array("name" => "David P.", "text" => "Bez ikakvih neprijetnosti i nakon duljeg nošenja."),
    array("name" => "Tin L.", "text" => "Idealne za svakodnevnu upotrebu."),
    array("name" => "Ognjen R.", "text" => "Ne podižu se, cijeli dan stoje kako treba."),
    array("name" => "Slavko I.", "text" => "Boksarice vrhunske udobjei."),
    array("name" => "Janko S.", "text" => "Jako dobro balansiraju udobje i potporu."),
    array("name" => "Matej V.", "text" => "Nema skliskog osjećaja, sve je prirodno."),
    array("name" => "Ivan P.", "text" => "Drže oblik, ne rašire se."),
    array("name" => "Julijan D.", "text" => "Materijal je nevjerojatno fin."),
    array("name" => "Matko H.", "text" => "Gumica ne puca i ne savija se."),
    array("name" => "Vito Č.", "text" => "Kvaliteta puno bolja nego očekivano."),
    array("name" => "Bono K.", "text" => "Nisam znao da boksarice mogu biti ovako dobre."),
    array("name" => "Hrvoje U.", "text" => "Odlična ventilacija i osjećaj svježine."),
    array("name" => "Ladislav F.", "text" => "Nema trljanja ni pri dugom hodanju."),
    array("name" => "Mislav T.", "text" => "Udobne i kad je zelo toplo."),
    array("name" => "Vilim P.", "text" => "Najboljše boksarice za moju građu."),
    array("name" => "Ademir S.", "text" => "Nema znojenja, materijal super diše."),
    array("name" => "Harun J.", "text" => "Jako lagane i prozračne."),
    array("name" => "Noa M.", "text" => "Drže boju, ne blijede."),
    array("name" => "Tomislav Č.", "text" => "Super udobne čak i ispod traperica."),
    array("name" => "Valentin L.", "text" => "Nisam očekivao ovako dobar osjećaj."),
    array("name" => "Dario S.", "text" => "Stvarno odlične boksarice."),
    array("name" => "Leon N.", "text" => "Nosim ih vsak dan otkad sam ih kupil."),
    array("name" => "Vjekoslav J.", "text" => "Nema nabora ni uvijanja."),
    array("name" => "Dino P.", "text" => "Očekivao sam manje, dobio več."),
    array("name" => "Franjo S.", "text" => "Izvrsne čak i kad vozim bicikl."),
    array("name" => "Erik R.", "text" => "Topla preporuka svima."),
    array("name" => "Silvio M.", "text" => "Tkanina se ne pelca, sve ostaje glatko."),
    array("name" => "Zlatan G.", "text" => "Ne bježe prema gore, odlično."),
    array("name" => "Dalibor S.", "text" => "Idealne za muškarce s osjetljivom kožom."),
    array("name" => "Gorjan P.", "text" => "Gumica ne ostavlja tragove."),
    array("name" => "Barvan T.", "text" => "Sve pohvale za udobje."),
    array("name" => "Alan F.", "text" => "Ove boksarice su prava prelomnica."),
    array("name" => "Stjepan L.", "text" => "Materijal se brzo suši."),
    array("name" => "Marko Ž.", "text" => "Ne mrse se ispod hlača."),
    array("name" => "Vlado Š.", "text" => "Nema neugodnih mirisa ni nakon cijelog dana."),
    array("name" => "Luka R.", "text" => "Končno boksarice koje stoje kako treba."),
    array("name" => "Filip U.", "text" => "Lako se peru i ne gube oblik."),
    array("name" => "Boris K.", "text" => "Mekane i zelo izdržljive."),
    array("name" => "Ivan X.", "text" => "Najboljše u ovom cjenovnom rangu."),
    array("name" => "Bruno V.", "text" => "Stvarno se ne uvlače u nogavice."),
    array("name" => "Andro K.", "text" => "Jako sam zadovoljan materijalom."),
    array("name" => "Sandi B.", "text" => "Ne iritiraju kožu — veliki plus."),
    array("name" => "Kevin S.", "text" => "Super udobne, nosim ih vsak dan."),
    array("name" => "Matias P.", "text" => "Stvarno vrhunski osjećaj."),
    array("name" => "Martin V.", "text" => "Nakon mjesec dana sve kao novo."),
    array("name" => "Oskar L.", "text" => "Čvrste, a opet fleksibilne."),
    array("name" => "Dino J.", "text" => "Ne zatežu ni kad vježbam."),
    array("name" => "Nikola U.", "text" => "Jednostavno popolne."),
    array("name" => "Sven M.", "text" => "Ne rola se gumica, odlično napravljeno."),
    array("name" => "Robert P.", "text" => "Jedne od najudobnijih bokserica koje sam probao."),
    array("name" => "Karlo B.", "text" => "Svakako preporučujem."),
    array("name" => "Tomo S.", "text" => "Materijal koji resnično diše."),
    array("name" => "Hrvoje K.", "text" => "Odlične i za sport."),
    array("name" => "Davor Z.", "text" => "Nemam nijednu primjedbu."),
    array("name" => "Danilo F.", "text" => "Vrijedi svake kune."),
    array("name" => "Mirko K.", "text" => "Nosim ih vsak dan — popolne."),
    array("name" => "Sebastian R.", "text" => "Bez greške. Kupujem opet.")
);
?>
